-- Seed public.clients with the 72 existing outreach leads.
-- Run this in the Supabase SQL editor (postgres role bypasses RLS).
insert into public.clients (name, contact, status, priority, notes) values
  ('RIGANAILS', '+371 26922200 · @riganails', 'todo', 'hi', 'Riga – Centrs — Strelnieku iela 5 | Active IG only — no website at all.'),
  ('Nail ID Riga', 'via Fresha', 'todo', 'hi', 'Riga – Zemgale Suburb — Kalnciema iela 9A | Riverside premium nail studio — only on Fresha.'),
  ('nailed.it.riga', '@nailed.it.riga', 'todo', 'hi', 'Riga – Centrs — Strelnieku iela 13 | Open 10–23 daily — Fresha-only.'),
  ('Glamour Nails Santa', 'via Fresha', 'todo', 'hi', 'Riga – Vidzeme Suburb — Brivibas gatve 224 | Manicure/pedicure/nail art — Fresha-only.'),
  ('Nails & Pearls', 'via Fresha', 'todo', 'hi', 'Riga – Centra rajons — Marijas iela 23 | Manikira studija — Fresha-only.'),
  ('kinyanails', 'via Fresha', 'todo', 'hi', 'Riga – Old Riga — Aspazijas bulvaris 32 | Cozy 1-chair studio, master Kintija — Fresha-only.'),
  ('Diamond Nails Riga', 'via Fresha', 'todo', 'hi', 'Riga – Vidzeme Suburb — Braslas iela 29 | Fresha-only.'),
  ('YOULI', 'via Fresha', 'todo', 'hi', 'Riga – Centrs — Katrinas iela 16A | Fresha-only.'),
  ('LE STUDIO', 'via Fresha', 'todo', 'hi', 'Riga – Centra rajons — Baznicas iela 20/22 | Manicure/pedicure team — Fresha-only.'),
  ('Reussi Studio', 'via Fresha', 'todo', 'hi', 'Riga – Centra rajons | 5.0 rating (53 reviews) — Fresha-only.'),
  ('Miami Nails', 'via Fresha', 'todo', 'hi', 'Riga – Centra rajons | 4.9 rating (944 reviews) — busy, Fresha-only.'),
  ('Podologs Agate Serzante', 'via Fresha', 'todo', 'hi', 'Riga – Centra rajons — Perses iela 16 | Pedicure & foot-care specialist — Fresha-only.'),
  ('Nagu Meistari', '@nagu_meistari', 'todo', 'hi', 'Riga | 3000+ followers, 24/7 booking link in bio. No website.'),
  ('MyNails Riga', '@mynails_riga', 'todo', 'hi', 'Riga – Centrs — Krisjana Valdemara iela 45 | 3300+ followers, IG only.'),
  ('Lemonail Riga', '@lemonail.riga', 'todo', 'hi', 'Riga – Centrs | Small IG-only studio.'),
  ('Manikirs Akvarele', '@manikirs.akvarele', 'todo', 'hi', 'Riga | IG-only nail/design studio.'),
  ('Noir Studio', 'via Instagram only', 'todo', 'hi', 'Riga | Manicure/pedicure, IG-only.'),
  ('Family Hair', 'via Fresha', 'todo', 'hi', 'Riga – Centra rajons — Tallinas iela 38 | Family-friendly salon — Fresha-only.'),
  ('Hairport Studija', 'via Fresha', 'todo', 'hi', 'Riga – Grizinkalns — Lienes iela 10 | Modern hair studio — Fresha-only.'),
  ('Dzirnavu 56 Salon', 'via Fresha', 'todo', 'hi', 'Riga – Centrs — Brivibas iela 40 | Hair salon — Fresha-only.'),
  ('Riga Frizetava', 'via Fresha', 'todo', 'hi', 'Riga – Latgale Suburb — Zemitana iela 6 | Family hair salon — Fresha-only.'),
  ('Skaistumkopsanas Salons Riga', '+371 67213123 · @rigatophair', 'todo', 'hi', 'Riga — Stabu iela 29 | IG-forward, no real website.'),
  ('REGI Salons', '@regi.salons', 'todo', 'hi', 'Riga | IG-only, self-described ''best beauty salon''.'),
  ('Skropstu Studija', '@skropstu_studija', 'todo', 'hi', 'Riga – Teika — Burtnieku iela 36a | 5400+ followers, 9+ yrs — no website.'),
  ('Madam Lashes', '@madamlashes_', 'todo', 'hi', 'Riga | IG-only lash studio.'),
  ('Evija Lashes', '@evija_lashes_riga', 'todo', 'hi', 'Riga | Solo master, 18 yrs experience. IG only.'),
  ('Acis.ka', '@acis.ka', 'todo', 'hi', 'Riga | IG-only lash extensions.'),
  ('Skropstu Pieaudzesana', '@skropstupieaudzesana.lv', 'todo', 'hi', 'Riga | IG-only lash & brow lamination.'),
  ('Hanifa PMU', '@hanifa_pmu', 'todo', 'hi', 'Riga | 5400+ followers PMU artist. IG only.'),
  ('Linda Ezera PMU', '@pmu_lindaezera', 'todo', 'hi', 'Riga | PMU lips/brows. IG only.'),
  ('Santa Guru Makeup', '@santaguruu', 'todo', 'hi', 'Riga | Celebrity makeup artist. IG only.'),
  ('Kosmetologs Jurmala', '@kosmetologs.jurmala', 'todo', 'hi', 'Jurmala | IG-only cosmetologist.'),
  ('Ilze Rimma Privatprakse', '@ilzes.rimmas.privatprakse', 'todo', 'hi', 'Liepaja | 20 yrs experience, IG-only.'),
  ('SIBI Beauty Salon', '+371 27272510 · @sibi.beautysalon', 'todo', 'hi', 'Riga – Old Riga — Jekaba iela 26/28 | Strong brand, good reviews — only a Versum booking page.'),
  ('Asia Spa Thai Massage', 'via Fresha', 'todo', 'hi', 'Riga – Centrs — Dzirnavu iela 55 | Thai massage — Fresha-only.'),
  ('Harmonia Studio', 'via Fresha', 'todo', 'hi', 'Riga – Centrs — Aleksandra Caka iela 33 | Wellness studio — Fresha-only.'),
  ('SYRINGA Facial Studio', 'via Fresha', 'todo', 'hi', 'Riga – Centrs — Blaumana iela 11/13 | Facial studio — Fresha-only.'),
  ('LAIMALUX Beauty Salon', '+371 29395087 · @laimaluxofficial', 'todo', 'hi', 'Riga | IG-only. No website found.'),
  ('Love My Life Beauty Salon', '+371 20008393 · salonslovemylife@gmail.com · @lovemylifebeautysalon', 'todo', 'hi', 'Riga — Uzvaras Bulvaris 10 | Has public email — easy to cold-email. FB/IG only.'),
  ('Nails by Ieva', '@nails.by_ieva', 'todo', 'hi', 'Jelgava | Gel/extensions/pedicure, booking via DM. IG only.'),
  ('Skaistuma Era', '@skaistumaera', 'todo', 'hi', 'Jelgava | Largest salon in Jelgava, 150+ services — IG-forward (verify site).'),
  ('SKY BEAUTY', 'fb:skybeautyjelgava', 'todo', 'hi', 'Jelgava | Hair/nails/cosmetology/solarium. FB only.'),
  ('Strogonovs', '+371 67283122 / +371 27702277 · strogonovs.lv', 'todo', 'med', 'Riga – Centrs — Marijas iela 8 | Outdated website — redesign pitch is strong.'),
  ('Salons Vecriga', 'salonsvecriga.lv', 'todo', 'med', 'Riga – Old Riga | Older site — redesign angle.'),
  ('Amane SPA', '+371 28213790 · amanespa@gmail.com · amanespa.lv', 'todo', 'low', 'Riga – Old Riga — Vagnera iela 14 | Has site — pitch redesign/upgrade only.'),
  ('Old Riga Spa', '+371 29340341 · info@oldrigaspa.lv · oldrigaspa.lv', 'todo', 'low', 'Riga – Old Riga — Kaleju iela 39 | Has site + Versum.'),
  ('Velvet Beauty', 'velvetbeauty.lv', 'todo', 'low', 'Riga – Centrs | Has modern-ish site.'),
  ('Siluets', '+371 25150058 · siluetsriga.lv', 'todo', 'low', 'Riga – Centrs — Matisa iela 19 | Has website.'),
  ('International Manicure Studio', '+371 20004588 · info@manikirs.lv · manikirs.lv', 'todo', 'low', 'Riga — Ernesta Birznieka-Upisa 20A | Has site.'),
  ('MooN Beauty Studio', 'manikirs-riga.lv', 'todo', 'low', 'Riga | Has site.'),
  ('ONE Beauty', '+371 28857000 · @one.beauty.nails · onebeauty.lv', 'todo', 'low', 'Riga – Plavnieki — Andreja Saharova iela 30 (TC Augusts) | Has site.'),
  ('Catrin Salons', 'catrinsalons.lv', 'todo', 'low', 'Riga | Has site.'),
  ('NailTime', '@nailtimelv · nailtime.lv', 'todo', 'low', 'Riga – Centrs | Has site.'),
  ('NailBee', 'nailbee.lv', 'todo', 'low', 'Riga | Has site.'),
  ('Divi Meistari', '@divimeistari · divimeistari.lv', 'todo', 'low', 'Riga – Centrs | Has site.'),
  ('Grieze', 'grieze.lv', 'todo', 'low', 'Riga | Has site.'),
  ('HairRiga Olimpia', '+371 25908271 · hairriga.com', 'todo', 'low', 'Riga – TC Olimpia — Olimpia mall, 2nd floor | Has site (chain).'),
  ('Salons Katrina', '+371 26605502 · salonskatrina@gmail.com · salonskatrina.lv', 'todo', 'low', 'Riga — Hospitalu iela 5 | Has site + email.'),
  ('BAGIRA', '+371 22831315 · bagira.lv', 'todo', 'low', 'Riga – Ziepniekkalns — Islices iela 1 | Has site.'),
  ('Salons MAIJA', '+371 67505193 / +371 25400103 · maija.lv', 'todo', 'low', 'Riga — Valdemara iela 16 | Has site (multi-location).'),
  ('Silvana', '+371 29293317 · silvana.lv', 'todo', 'low', 'Riga – Centrs | Has site.'),
  ('Saules Salons', '+371 22087688 · saulessalons.lv', 'todo', 'low', 'Riga – Centrs — Stabu iela 14 | Has site.'),
  ('Skaistuma Pietura', 'skaistumapietura.lv', 'todo', 'low', 'Riga – Ciekurkalns | Has site.'),
  ('Glorija Salons', '+371 20208118 · gloria-salons.lv', 'todo', 'low', 'Riga — Rupniecibas iela 3 | Has site.'),
  ('Brows by Karlina', 'bbk.lv', 'todo', 'low', 'Riga | Has site.'),
  ('Lash & Brow Studio Riga', 'lashandbrow.lv', 'todo', 'low', 'Riga | Has site.'),
  ('Nautika', '+371 29429444 / +371 63422210 · nautika.lv', 'todo', 'low', 'Liepaja — Frica Brivzemnieka iela 38 | Has site.'),
  ('Nova Clinic', 'arstskosmetologs.lv', 'todo', 'low', 'Jurmala | Has site (clinic).'),
  ('ERA Esthetic', '+371 20511113 · info@eraesthetic.lv · eraesthetic.lv', 'todo', 'low', 'Jurmala | Has site + email.'),
  ('BABOR Beauty Spa', '+371 22333131 · info@baborbeautyspa.lv · baborbeautyspa.lv', 'todo', 'low', 'Riga – Centrs — Gertrudes iela 9 | Has site (brand-backed).'),
  ('Taka Spa', 'takaspa.lv', 'todo', 'low', 'Riga | Has site.'),
  ('VSpa', '+371 26961181 · vspa.lv', 'todo', 'low', 'Riga | Has site.');
