-- Unified seed: ALL leads (beauty + prospects), categorized.
alter table public.clients add column if not exists category text;
truncate public.clients;   -- replaces the old 72 with the full set; run BEFORE marking contacted
insert into public.clients (name, contact, category, status, priority, notes) values
  ('Céleste Beauty', '+371 24 559 321 · IG @celeste.beauty.riga', 'kosmetika', 'todo', 'med', 'Estētiskais salons · Pļavnieki | Nav lapas, tikai IG. Jauns estētisks salons, vērtējums 4.9.'),
  ('SPA speciālists Olga', '+371 26 740 603 · IG @spa.specialist.olga', 'spa', 'todo', 'med', 'SPA / masāža · solo | Nav lapas, tikai IG. Solo SPA/masāža, vērtējums 5.0.'),
  ('kukas_riga', '+371 29 526 419 · IG @kukas_riga', 'konditoreja', 'todo', 'med', 'Tortes pēc pasūtījuma | Nav lapas, tikai IG.'),
  ('Charme nail room', '+371 27 005 432', 'nagi', 'todo', 'med', 'Manikīrs · Purvciems | 48 atsauksmes. IG handle meklē pēc nosaukuma.'),
  ('Patisserie Tortes namiņš', '+371 25 777 995 · FB tortesnamins2018', 'konditoreja', 'todo', 'med', 'Konditoreja · pasūtījumi | Tikai FB.'),
  ('DoGroom', '+371 29 515 025 · FB dogrooom.lv', 'dzivnieki', 'todo', 'med', 'Suņu / kaķu frizētava | Tikai FB lapa, 24 atsauksmes.'),
  ('Salons NOA', '+371 67 591 777', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons | 67 atsauksmes, nav īstas lapas.'),
  ('Dzīvnieku frizētava', '+371 29 130 181', 'dzivnieki', 'todo', 'med', 'Suņu frizētava · Vācieša iela | Solo suņu frizētava (Rouber Groom).'),
  ('Skaistuma salons DANI', '+371 29 533 187 · danisalons.wixsite.com', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons | danisalons.wixsite.com'),
  ('Cepu tortas', '+371 28 645 776 · ceputortes.lv', 'konditoreja', 'todo', 'med', 'Konditoreja | ceputortes.lv'),
  ('Franču Maize', '+371 67 293 252 · francumaize.lv', 'konditoreja', 'todo', 'med', 'Konditoreja Rīgā / maiznīca | francumaize.lv'),
  ('nailed.it.riga', 'IG @nailed.it.riga · Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. Strēlnieku iela 13.'),
  ('Glamour Nails Santa', 'Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Teika | Nav lapas, tikai Fresha. Brīvības gatve 224.'),
  ('Nails & Pearls', 'FB · Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. Marijas iela 23.'),
  ('kinyanails', 'Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Vecrīga | Nav lapas (meistare Kintija). Aspazijas bulvāris 32.'),
  ('Diamond Nails Riga', 'Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Purvciems | Nav lapas, tikai Fresha. Braslas iela 29.'),
  ('YOULI', 'IG @youli_studio · Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. Katrīnas iela 16A.'),
  ('Reussi Studio', 'IG @reussi.studio · Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Vecrīga | Nav lapas. Aspazijas bulvāris 32.'),
  ('Miami Nails', 'IG @miami.beauty.salon · Fresha', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. Alberta iela 1.'),
  ('Podologs Agate Seržante', 'Fresha', 'nagi', 'todo', 'med', 'Podoloģija · Centrs | Nav lapas, tikai Fresha. Pērses iela 16.'),
  ('MyNails Riga', 'IG @mynails_riga · FB', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. K. Valdemāra iela 45.'),
  ('Lemonail Riga', 'IG @lemonail.riga · FB', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. A. Čaka iela 70.'),
  ('Manikirs Akvarele', '+371 24878688 · IG @manikirs.akvarele · FB', 'nagi', 'todo', 'med', 'Nagu studija · Rīga | Nav lapas. Pieraksts SMS.'),
  ('Noir Studio', '+371 28 446 774 · IG @noir.nailstudio · FB', 'nagi', 'todo', 'med', 'Nagu studija · Centrs | Nav lapas. Stabu iela 59.'),
  ('Family Hair', '+371 20 000 441 · Fresha', 'frizieri', 'todo', 'med', 'Frizētava · Centrs | Lapa nedarbojas; tikai Fresha. Tallinas iela 38.'),
  ('Dzirnavu 56 Salon', 'Fresha', 'frizieri', 'todo', 'med', 'Frizētava · Centrs | Nav lapas, tikai Fresha. Brīvības iela 40.'),
  ('Riga Frizetava', '+371 20000441 · FB · Fresha', 'frizieri', 'todo', 'med', 'Frizētava · Grīziņkalns | Nav lapas. FB + Fresha. Zemitāna iela 6.'),
  ('Madam Lashes', 'IG @madamlashes_', 'skropstas', 'todo', 'med', 'Skropstu studija · Rīga | Nav lapas, tikai IG.'),
  ('Evija Lashes', '+371 29950044 · IG @evija_lashes_riga', 'skropstas', 'todo', 'med', 'Skropstu/uzacu studija · Ziepniekkalns | Nav lapas, tikai IG.'),
  ('Acis.ka', 'IG @acis.ka', 'skropstas', 'todo', 'med', 'Skropstu studija · Rīga | Nav lapas, tikai IG.'),
  ('Hanifa PMU', 'IG @hanifa_pmu', 'kosmetika', 'todo', 'med', 'Permanentais grims · Rīga | Nav lapas, tikai IG.'),
  ('Kosmetologs Jūrmala', 'IG @kosmetologs.jurmala · FB', 'kosmetika', 'todo', 'med', 'Kosmetoloģija · Jūrmala | Nav lapas. IG + FB.'),
  ('Ilze Rimma Privātprakse', 'IG @ilzes.rimmas.privatprakse', 'kosmetika', 'todo', 'med', 'Kosmetoloģija · Liepāja | Nav lapas, tikai IG.'),
  ('Asia Spa Thai Massage', '+371 23279009 · IG @asia_spa_riga · Fresha', 'spa', 'todo', 'med', 'Taizemes masāža / SPA · Centrs | Nav lapas. Dzirnavu iela 55.'),
  ('Harmonia Studio', '29161193 · Fresha', 'spa', 'todo', 'med', 'Spa / Wellness · Centrs | Nav lapas, tikai Fresha. A. Čaka iela 33.'),
  ('SYRINGA Facial Studio', 'Fresha', 'spa', 'todo', 'med', 'Skaistumkopšana · Centrs | Nav lapas, tikai Fresha. Blaumaņa iela 11/13.'),
  ('Love My Life Beauty Salon', '+371 20008393 · IG @lovemylifebeautysalon · FB', 'saloni', 'todo', 'med', 'Skaistumkopšana · Pārdaugava | Nav lapas. Uzvaras bulvāris 10 (Pepsi centrs).'),
  ('Nails by Ieva', 'IG @nails.by_ieva', 'nagi', 'todo', 'med', 'Nagu studija · Jelgava | Nav lapas, tikai IG.'),
  ('SKY BEAUTY', '+371 20177678 · FB', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons · Jelgava | Nav lapas, tikai FB. Svētes iela 7.'),
  ('Nail ID Riga', '+371 22 334 758 · IG @nailidriga · nailidriga.com', 'nagi', 'todo', 'med', 'Nagu studija · Āgenskalns | Sava lapa nailidriga.com (jāpārbauda). Kalnciema iela 9A.'),
  ('LE STUDIO', '+371 67282323 · IG @salons_le_studio · FB · le-studio.lv', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons · Centrs | Novecojusi lapa le-studio.lv. Baznīcas iela 20/22.'),
  ('Skaistumkopšanas Salons Riga', '+371 67213123 · IG @rigatophair · FB · rigatophair.lv', 'frizieri', 'todo', 'med', 'Frizētava · Centrs | Novecojusi lapa rigatophair.lv. Stabu iela 29.'),
  ('REGI Salons', '+371 20040425 · IG @regi.salons · FB · regisalons.lv', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons · Teika | Novecojusi lapa regisalons.lv. Dārzaugļu iela 1.'),
  ('Skropstu Studija', '25414376 · IG @skropstu_studija · skropstustudija.lv', 'skropstas', 'todo', 'med', 'Skropstu studija · Teika | Novecojusi lapa skropstustudija.lv. Burtnieku iela 36a.'),
  ('Skropstu Pieaudzēšana', '+371 25550745 · skropstupieaudzesana.lv · Timma', 'skropstas', 'todo', 'med', 'Skropstu studija · Centrs | Novecojusi lapa skropstupieaudzesana.lv. Ģertrūdes iela 9.'),
  ('LAIMALUX Beauty Salon', '+371 29395087 · IG @laimaluxofficial · FB · laimalux.lv', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons · Centrs | Lapa laimalux.lv apturēta. Brīvības iela 43. (Laimas Vaikules salons)'),
  ('Strogonovs', '+371 67283122 · FB · strogonovs.lv', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons · Centrs | Novecojusi lapa strogonovs.lv. Marijas iela 8.'),
  ('Salons Vecrīga', '+371 28239502 · FB · salonsvecriga.lv', 'saloni', 'todo', 'med', 'Skaistumkopšanas salons · Vecrīga | Novecojusi lapa salonsvecriga.lv. Teātra iela 2.'),
  ('Atlas Motors', '+37167310382 · Facebook · info@atlasmotors.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · 38 | Ir tikai Facebook lapa — nav īstas mājaslapas'),
  ('Dumbrāja autoserviss', '+37126538975 · Facebook · info@dumbrajaautoserviss.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · Bēķi | Ir tikai Facebook lapa — nav īstas mājaslapas'),
  ('Reaktors', '+37167509210 · Facebook · reaktors@reaktors.lv', 'frizieri', 'todo', 'hi', 'Frizētavas · 4 | Ir tikai Facebook lapa — nav īstas mājaslapas'),
  ('AB Intelligence Services', '+37126112939 · info@abintelligenceservices.com · abintelligenceservices.com', 'juristi', 'todo', 'hi', 'Juristi / advokāti · 162 | Lapa nedarbojas vai atgriež kļūdu; Nav HTTPS — nedroša; Trūkst meta apraksta (SEO)'),
  ('Verbo', '+37167224100 · verbo@verbo.lv · verbo.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · 15 | Lapa nedarbojas vai atgriež kļūdu; Nav pielāgota telefoniem; Trūkst meta apraksta (SEO)'),
  ('ARVUS', '+37163125878 · info@arvus.lv · arvus.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · 6 | Nav HTTPS — nedroša; Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('Armando auto', '+37126390582 · info@armandoauto.lv · armandoauto.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · 8A | Lapa nedarbojas vai atgriež kļūdu'),
  ('Valdeko', '+37164233721 · valdeko@valdeko.lv · valdeko.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · Valmiera | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Novecojis saturs (2016); Gandrīz tukša / placeholder lapa'),
  ('Autofit', '+37120444770 · serviss@auto-fit.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · Autofit | Ir savs domēns, bet nav mājaslapas'),
  ('Ramus auto serviss', '+37125555270 · info@ramusauto.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · 61 | Ir savs domēns, bet nav mājaslapas'),
  ('Signāls EM', '+37164823450 · signalsem@signalsem.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · 21 | Ir savs domēns, bet nav mājaslapas'),
  ('Valdzers un Ko', '+37163291818 · info@valdzers.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · Valdzers un Ko | Ir savs domēns, bet nav mājaslapas'),
  ('Komene', '+37167821019 · komene@elidars.lv', 'frizieri', 'todo', 'hi', 'Frizētavas · 15 | Ir savs domēns, bet nav mājaslapas'),
  ('NikoModa', '+37128261813 · info@nikomoda.lv', 'frizieri', 'todo', 'hi', 'Frizētavas · 4 | Ir savs domēns, bet nav mājaslapas'),
  ('Averdo', '+37126559355 · info@averdo.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · 37 | Ir savs domēns, bet nav mājaslapas'),
  ('Cubera', '+37127451919 · info@cubera.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · 32B | Ir savs domēns, bet nav mājaslapas'),
  ('Daces Grinbergas juridiskais birojs', '+37167278220 · info@jurists.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · Skolas iela | Ir savs domēns, bet nav mājaslapas'),
  ('Femida', '+37129750075 · legal@femida.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · Rīga | Ir savs domēns, bet nav mājaslapas'),
  ('Grāmatvedības pakalpojumi JUMS', '+37126314064 · info@gpjums.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · Hipokrāta iela | Ir savs domēns, bet nav mājaslapas'),
  ('K&K Law Office', '+37126289662 · info@kklaw.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · 94 | Ir savs domēns, bet nav mājaslapas'),
  ('LEX AURUM', '+37129574890 · aivars@lexaurum.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · Brāļu Kaudzīšu iela | Ir savs domēns, bet nav mājaslapas'),
  ('Visa Vērte', '+37129279176 · visaverte@visaverte.lv', 'juristi', 'todo', 'hi', 'Juristi / advokāti · 19/21 | Ir savs domēns, bet nav mājaslapas'),
  ('Paviljons Ziedoņdārzs', '+37124844627 · paviljons@ziedondarzs.lv', 'restorani', 'todo', 'hi', 'Restorāni / kafejnīcas · 100 | Ir savs domēns, bet nav mājaslapas'),
  ('EOSA', '+37167969522 · info@eosabeauty.com', 'saloni', 'todo', 'hi', 'Skaistumkopšana · Stabu iela | Ir savs domēns, bet nav mājaslapas'),
  ('Roze', '+37128633405 · roze@salonsroze.lv', 'saloni', 'todo', 'hi', 'Skaistumkopšana · 7 | Ir savs domēns, bet nav mājaslapas'),
  ('Krokus un Ko', '+37167414856 · info@vajagzobarstu.lv', 'zobarsti', 'todo', 'hi', 'Zobārsti · 32 | Ir savs domēns, bet nav mājaslapas'),
  ('DTC', '+37167367748 · info@dtcauto.lv · dtcauto.lv', 'autoservisi', 'todo', 'hi', 'Autoservisi · Rīga | Nav HTTPS — nedroša; Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Novecojis saturs (2005)'),
  ('Elizeja', '+37167808180 · salons@elizeja.lv · elizeja.lv', 'frizieri', 'todo', 'med', 'Frizētavas · 6 | Nav pielāgota telefoniem; Trūkst lapas virsraksta (SEO); Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('RT Tax Latvia', '+37167630931 · info@rttax.lv · rttax.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 15 k-1 | Nav pielāgota telefoniem; Trūkst lapas virsraksta (SEO); Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('Glazūra AG', '+37129515762 · glazura@glazura.lv · glazura.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · Zolitūdes iela | Nav HTTPS — nedroša; Trūkst meta apraksta (SEO); Novecojis kods (<font>); Novecojis saturs (2017)'),
  ('AT grāmatvedība un audits', '+37129266622 · anita@ataudits.lv · ataudits.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 450B | Nav HTTPS — nedroša; Nav pielāgota telefoniem; Trūkst lapas virsraksta (SEO); Trūkst meta apraksta (SEO)'),
  ('Varāns', '+37126437437 · office@varans.lv · varans.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · 72B | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('AMTIG', '+37125550557 · info@amtig.lv · amtig.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · 162A | Nav pielāgota telefoniem; Novecojuši efekti (marquee/blink); Novecojis saturs (2013)'),
  ('AO kolekcija', '+37167399135 · info@aokolekcija.lv · aokolekcija.lv', 'frizieri', 'todo', 'med', 'Frizētavas · 52 | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('Silenta', '+37122830082 · silenta@silenta.lv · silenta.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · Rīga | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('DOKUMENTS', '+37128858997 · andrei@arnautov.lv · arnautov.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 149 | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Gandrīz tukša / placeholder lapa'),
  ('Nikaserviss', '+37167332040 · nikaserviss@nikaserviss.lv · nikaserviss.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · Pet City | Lapa bloķē automātisko pārbaudi — jāpārbauda manuāli; Nav pielāgota telefoniem; Trūkst meta apraksta (SEO)'),
  ('Belisa', '+37129174185 · info@belisa.lv · belisa.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 11 k-1 | Lapa bloķē automātisko pārbaudi — jāpārbauda manuāli; Nav pielāgota telefoniem; Trūkst meta apraksta (SEO)'),
  ('Auto darbnīca Riepulis', '+37122846696 · riepulis@riepulis.lv · riepulis.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · 22 | Lapa bloķē automātisko pārbaudi — jāpārbauda manuāli; Trūkst meta apraksta (SEO)'),
  ('Smartech', '+37122352698 · smartech@smartech.lv · smartech.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · 22 | Lēna ielāde (3.4s); Nav pielāgota telefoniem; Novecojis saturs (2014)'),
  ('Mēness boulings', '+37167840505 · info@bowling.lv · bowling.lv', 'restorani', 'todo', 'med', 'Restorāni / kafejnīcas · Mēness boulinga centrs | Nav pielāgota telefoniem; Novecojis kods (<font>); Novecojis saturs (2006)'),
  ('2R Auto', '+37122310405 · r.r.auto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 3 | Nav mājaslapas'),
  ('A & C Motors', '+37126101153 · acmotors@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Mehanizācijas iela | Nav mājaslapas'),
  ('A.S. Technic', '+37128306080 · rempaks@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 7 | Nav mājaslapas'),
  ('ABM Auto', '+37129247799 · abmauto@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 5 | Nav mājaslapas'),
  ('AGM', '+37129251259 · agm@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 79 | Nav mājaslapas'),
  ('AMS Stende', '+37123477735 · amsstende@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 49 | Nav mājaslapas'),
  ('AUTO RAJ', '+37129909030 · sorento68@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 20 | Nav mājaslapas'),
  ('AUTODARBNĪCA 333', '+37126147348 · autodarbnica@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Druvas | Nav mājaslapas'),
  ('AV Motorsports', '+37129213095 · veismanis.av@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 330 | Nav mājaslapas'),
  ('Altair', '+37129229175 · altair.serviss@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 82D | Nav mājaslapas'),
  ('Ar auto serviss', '+37129108805 · arautoserviss@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 3A | Nav mājaslapas'),
  ('Archi Auto', '+37126720080 · archiauto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 35 | Nav mājaslapas'),
  ('Arfila', '+37167143867 · arfila@latnet.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 7 | Nav mājaslapas'),
  ('Auto Mūris', '+37164233323 · automuris@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 5 | Nav mājaslapas'),
  ('Auto Profs 1', '+37126412498 · autoprofs21@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 17 | Nav mājaslapas'),
  ('Auto Puma', '+37129162022 · autopuma2@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 13 | Nav mājaslapas'),
  ('Auto SOS Klubs 1', '+37129197595 · autososklubs1@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Cēsu prospekts | Nav mājaslapas'),
  ('Auto kruīzs', '+37129112111 · autokruizs.balvi@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 7 | Nav mājaslapas'),
  ('Auto priekam', '+37129515233 · janiskli@inbox.lv ', 'autoservisi', 'todo', 'low', 'Autoservisi · 2B | Nav mājaslapas'),
  ('Auto virsbūvju serviss', '+37128339018 · akarzjuks@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 9 | Nav mājaslapas'),
  ('Auto-Spar', '+37163013854 · autospar2004@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 20 | Nav mājaslapas'),
  ('Autoelektro', '+37126565875 · ugaleserviss@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · Austrumi | Nav mājaslapas'),
  ('Aviators', '+37167207885 · sia.aviators@mail.ru', 'autoservisi', 'todo', 'low', 'Autoservisi · airBaltic | Nav mājaslapas'),
  ('Balt-Serviss', '+37125155110 · baltserviss@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 136 | Nav mājaslapas'),
  ('Brothers', '+37129941186 · madars21@jahoo.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 1 | Nav mājaslapas'),
  ('CH 150', '+37122181700 · irgovs@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Zemkopības institūts | Nav mājaslapas'),
  ('DZ Automeistars', '+37129470567 · dzautomeistars@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · DZ Automeistars | Nav mājaslapas'),
  ('Dalis', '+37129204237 · dalis@e-apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Salaspils | Nav mājaslapas'),
  ('Dambis Serviss', '+37129203377 · dambisserviss@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 24 k-1 | Nav mājaslapas'),
  ('Danivi serviss', '+37167936121 · daniviserviss@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Ķekava | Nav mājaslapas'),
  ('Darbnīca K', '+37165122227 · darbnicak@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 11 | Nav mājaslapas'),
  ('Dzinča', '+37129464854 · dzinca01@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · SIA Dzinča | Nav mājaslapas'),
  ('Evert auto', '+37126335684 · evertauto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 1 | Nav mājaslapas'),
  ('Francijas Auto', '+37129515732 · francijasauto@dot.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Romāni | Nav mājaslapas'),
  ('GP motors', '+37122385050 · girtsperevalovs@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · Grandiņi 1 | Nav mājaslapas'),
  ('Garants auto', '+37129611987 · garantauto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 121 | Nav mājaslapas'),
  ('Gaspars Racing Team', '+37127843441 · gasparsracingteam@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 9 | Nav mājaslapas'),
  ('Helms 1', '+37126897573 · savirze@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 2 | Nav mājaslapas'),
  ('Hestija', '+37164522185 · hestija.vip@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 7 | Nav mājaslapas'),
  ('Hārdeks', '+37129344484 · hardeks-aac@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Lāčplēši | Nav mājaslapas'),
  ('I & I Serviss', '+37128626622 · iuniserviss@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Brīvības iela | Nav mājaslapas'),
  ('I.R. Auto', '+37122337070 · shadow.line@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 26 | Nav mājaslapas'),
  ('Izdarīgs', '+37167426389 · izdarigs2@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 1 | Nav mājaslapas'),
  ('JD Auto', '+37129245506 · diura@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 21 | Nav mājaslapas'),
  ('Jura auto serviss', '+37129242556 · rudakovs@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 21A | Nav mājaslapas'),
  ('KN Serviss', '+37167135925 · kn-serviss@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 6 | Nav mājaslapas'),
  ('KR Motors', '+37129235476 · krmotors@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 7 | Nav mājaslapas'),
  ('Katram Auto', '+37129459594 · katramauto@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 5 | Nav mājaslapas'),
  ('Kores', '+37129520355 · ixc@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Kores | Nav mājaslapas'),
  ('MCS serviss', '+37163821233 · mcsserviss@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 90 | Nav mājaslapas'),
  ('MSdiag', '+37126259495 · oskars.petersons@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 73 | Nav mājaslapas'),
  ('Maksis MT', '+37164022518 · maksis27@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 3 | Nav mājaslapas'),
  ('Medeo', '+37165067782 · medeo@e-apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 8 | Nav mājaslapas'),
  ('NI Auto', '+37129171500 · nil@balticom.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 6 | Nav mājaslapas'),
  ('Niko', '+37126384218 · nikoauto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Dārza iela/Rīgas Stradiņa universitāte | Nav mājaslapas'),
  ('Pit Stop', '+37163807031 · pitstop@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 87 | Nav mājaslapas'),
  ('Protekss', '+37128635126 · edk.auto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 1 | Nav mājaslapas'),
  ('Pārtinēji un partneri', '+37128353857 · partineji@tvnet.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Ķekava | Nav mājaslapas'),
  ('RP Servis', '+37128330220 · sia.rpservis@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 2B | Nav mājaslapas'),
  ('Ritms R', '+37165622155 · ac-ritms@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Rēzekne | Nav mājaslapas'),
  ('Rubīns-3', '+37129418468 · rubins42@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 44 | Nav mājaslapas'),
  ('SVA', '+37129247785 · svaauto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 8 | Nav mājaslapas'),
  ('Sailers', '+37167274147 · sailer@one.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 37 | Nav mājaslapas'),
  ('Serģis un dēli', '+37164122216 · ksergis@one.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Serģis un dēli | Nav mājaslapas'),
  ('Sigma Dobele', '+37163781454 · sigmaauto@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Liepāja | Nav mājaslapas'),
  ('Siguldas AutoCentrs', '+37120061977 · siguldas-autocentrs@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 2C | Nav mājaslapas'),
  ('Silavas Servisa Centrs', '+37129110607 · ssc@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 2 | Nav mājaslapas'),
  ('Spīdola', '+37129227440 · ainars.spidola@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 18 | Nav mājaslapas'),
  ('Tech Drive', '+37120140009 · sia.techdrive@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 27A | Nav mājaslapas'),
  ('Tinda C', '+37164772147 · tindac@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Tinda C | Nav mājaslapas'),
  ('Topers', '+37167381243 ·  topersautocentrs@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 7A | Nav mājaslapas'),
  ('V-Serviss', '+37126343436 · riepas.com@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · Kebab City Sarkandugava | Nav mājaslapas'),
  ('Vitoserviss', '+37128350212 · vitoserviss1@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 6 | Nav mājaslapas'),
  ('Vērsītis', '+37129295676 · siaversitis@inbox.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 11 | Nav mājaslapas'),
  ('Zevs Custom Garage', '+37127153044 · zevscustomgarage@gmail.com', 'autoservisi', 'todo', 'low', 'Autoservisi · 3 | Nav mājaslapas'),
  ('Ziemeļvējš', '+37129917396 · edijs7@apollo.lv', 'autoservisi', 'todo', 'low', 'Autoservisi · 9 | Nav mājaslapas'),
  ('A-Z', '+37129711723 · tjermakova@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 106 | Nav mājaslapas'),
  ('Akcents', '+37128358266 · ingasfrizetava@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · Rīgas 69. pamatskola | Nav mājaslapas'),
  ('Baško salons Vija', '+37164233676 · basko_salons@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 2 | Nav mājaslapas'),
  ('Dane', '+37120149388 · medamltd@gmail.com', 'saloni', 'todo', 'low', 'Skaistumkopšana · 60A | Nav mājaslapas'),
  ('Demians', '+37163881596 · hotel.demians@gmail.com', 'frizieri', 'todo', 'low', 'Frizētavas · Rīgas 139. pirmsskolas izglītības iestāde | Nav mājaslapas'),
  ('Fantāzija', '+37167277310 · aprioli@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 109 | Nav mājaslapas'),
  ('Hēbe', '+37129299161 · ogonkova@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 4 | Nav mājaslapas'),
  ('Ideāls M', '+37129746933 · idealsm@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 422 | Nav mājaslapas'),
  ('Imidžs', '+37167217006 · Marina.nik.morozova@gmail.com', 'frizieri', 'todo', 'low', 'Frizētavas · 6 | Nav mājaslapas'),
  ('Ivonna Beauty', '+37167521158 · i.d.juglal@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · Mobilo telefonu serviss | Nav mājaslapas'),
  ('Kamilli', '+37163941314 · kamilli@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · Bauska | Nav mājaslapas'),
  ('Loreta', '+37129274656 · frizetavaloreta@gmail.com', 'frizieri', 'todo', 'low', 'Frizētavas · 161 | Nav mājaslapas'),
  ('Līze T', '+37167618548 · lize-t@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 6 | Nav mājaslapas'),
  ('MONA', '+37122514179 · vinde2@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 4 | Nav mājaslapas'),
  ('Man Cave', '+37128973219 · mancave.ventspils@gmail.com', 'frizieri', 'todo', 'low', 'Frizētavas · 2 | Nav mājaslapas'),
  ('Marite S', '+37167914753 · marite224@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · Jaņa Rozentāla Rīgas mākslas vidusskola | Nav mājaslapas'),
  ('Salons A', '+37167287155 · irena79@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 110A | Nav mājaslapas'),
  ('San San', '+37167456427 · borusik3@tvnet.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 70 | Nav mājaslapas'),
  ('Stils', '+37164471916 · guntrasproge@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 11 | Nav mājaslapas'),
  ('Tresor', '+37167299657 · tresor9@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 93 | Nav mājaslapas'),
  ('Versija', '+37167021597 · versija@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · 28 | Nav mājaslapas'),
  ('Vilana', '+37126955001 · rin-stars@inbox.lv', 'frizieri', 'todo', 'low', 'Frizētavas · Mākslinieku nams | Nav mājaslapas'),
  ('Šenona', '+37167376025 · zane.namike@gmail.com', 'frizieri', 'todo', 'low', 'Frizētavas · 76 | Nav mājaslapas'),
  ('Abikka', '+37167555550 · abikka@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · Ropaži | Nav mājaslapas'),
  ('Akvatorija', '+37129297169 · akvatorija77@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 21 | Nav mājaslapas'),
  ('Baltic Rise', '+37127050522 · baltic.rise@mail.ru', 'juristi', 'todo', 'low', 'Juristi / advokāti · 125 | Nav mājaslapas'),
  ('Dinar', '+37167442036 · georgcvetkov@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · Autofit | Nav mājaslapas'),
  ('ECB Assets', '+37129436564 · ralfs.nemiro@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 8 | Nav mājaslapas'),
  ('Ilear', '+37129905195 · ilear@apollo.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 2 | Nav mājaslapas'),
  ('Kodoliņš', '+37167322360 · koos@apollo.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · Pulkveža Brieža iela | Nav mājaslapas'),
  ('LM Juridiskais birojs', '+37129106228 · leonsmezeckis@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 58 | Nav mājaslapas'),
  ('Legists', '+37167382209 · legists@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · Rīga | Nav mājaslapas'),
  ('Liepiņš', '29106014 · rincha2@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 9 | Nav mājaslapas'),
  ('M un M risinājumi', '+37126359768 · briedis.martins@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · Aviācijas iela | Nav mājaslapas'),
  ('Rivengo', '+37167378448 · rivengo@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 96 | Nav mājaslapas'),
  ('Stelard', '+37128458977 · info.stelard@gmail.com', 'juristi', 'todo', 'low', 'Juristi / advokāti · 74 | Nav mājaslapas'),
  ('Trans Legal Consulting', '+37127840092 · tlc.company@inbox.lv', 'juristi', 'todo', 'low', 'Juristi / advokāti · 10 | Nav mājaslapas'),
  ('Baltā māja', '+37129518447 · kalpumaja@inbox.lv', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · Bauska | Nav mājaslapas'),
  ('Drava', '+37127708211 · kafedrava@inbox.lv', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · Rīgas 71. vidusskola | Nav mājaslapas'),
  ('Dzērves ligzda', '+37163490411	 · dzerves.ligzda@apollo.lv', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · 33 | Nav mājaslapas'),
  ('Miranda', '+37129116535 · kafe.miranda@inbox.lv', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · 160 k-14 | Nav mājaslapas'),
  ('Vidus un partneri', '+37164229450 · viduspartneri@inbox.lv', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · Valmiera | Nav mājaslapas'),
  ('Vilkābeles', '+37120228181 · solmaro@inbox.lv', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · Vilkābeles | Nav mājaslapas'),
  ('Āķagals', '+37129454450 · akagals.cafe@gmail.com', 'restorani', 'todo', 'low', 'Restorāni / kafejnīcas · 3 | Nav mājaslapas'),
  ('Aiga', '+37126386777 · rijards@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 1 | Nav mājaslapas'),
  ('Amisi SG', '+37124556244 · amisi@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 16 | Nav mājaslapas'),
  ('Bastet', '+37122666620 · bastetbeauty@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 6 | Nav mājaslapas'),
  ('Dani', '+37129533187 · danisalons@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 76 | Nav mājaslapas'),
  ('Deloni', '+37124868842 · deloni.lv@gmail.com', 'saloni', 'todo', 'low', 'Skaistumkopšana · 26 | Nav mājaslapas'),
  ('Elizabete', '+37126962519 · anzela.orlova@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · Rīgas brīvostas pārvaldes rotaļu laukums Meldru ielā 1A | Nav mājaslapas'),
  ('Evitas Lucas Skaistuma Studija', '+37120390193 · evitalucag12@gmail.com', 'saloni', 'todo', 'low', 'Skaistumkopšana · 46/48 | Nav mājaslapas'),
  ('Kate', '+37167327651 · korlandrein@gmail.com', 'saloni', 'todo', 'low', 'Skaistumkopšana · Ķekava | Nav mājaslapas'),
  ('Luxadore', '+37167627522 · salonsluxadore@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 56 | Nav mājaslapas'),
  ('More Beauty', '+37163029800 · morebeauty@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · Biznesa centrs Zemgale | Nav mājaslapas'),
  ('Secret of Beauty', '+37166660429 · secretofbeauty@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 250 | Nav mājaslapas'),
  ('Skaistuma studija', '+37127759145 · marinateraude876@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · Torņakalna baznīca | Nav mājaslapas'),
  ('Sofija', '+37129115837 · uzkalns2@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · Raiņa iela | Nav mājaslapas'),
  ('Šanté', '+37120450442 · shantee2@inbox.lv', 'saloni', 'todo', 'low', 'Skaistumkopšana · 22 | Nav mājaslapas'),
  ('A.Ķiesnera zobārstniecības privātprakse', '+37127888992 · ansis.kiesneris@inbox.lv', 'zobarsti', 'todo', 'low', 'Zobārsti · Rīgas namu pārvaldnieks | Nav mājaslapas'),
  ('Reliant', '+37167312065 · info@reliant.lv · reliant.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 20 | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Novecojis saturs (2009)'),
  ('Latvijas Drošības biznesa asociācija', '+37126133344 · ldba@scgroup.lv · scgroup.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 21 | Nav pielāgota telefoniem; Trūkst meta apraksta (SEO); Novecojis saturs (2019)'),
  ('Līvānu autocentrs', '+37165344272 · info@livanuautocentrs.lv · livanuautocentrs.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · 2A | Nav pielāgota telefoniem; Novecojis saturs (2010)'),
  ('Viduļi serviss', '+37129510677 · viduli@viduli.lv · viduli.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · Bauska | Nav pielāgota telefoniem; Novecojis saturs (2011)'),
  ('Zvērinātu advokātu birojs Markvarte/LEXCHANGE', '+37167812783 · zane@markvarte.lv · markvarte.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 19 k-1 | Nav pielāgota telefoniem; Novecojis saturs (2014)'),
  ('Fortis grupa', '+37167614409 · fortis@fortis.lv · fortis.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · SIA Alfards | Lēna ielāde (3.5s); Trūkst meta apraksta (SEO); Novecojis saturs (2021)'),
  ('Plintuss', '+37129435047 · info@plintuss.lv · plintuss.lv', 'autoservisi', 'todo', 'med', 'Autoservisi · 71A | Lēna ielāde (4.0s); Novecojis saturs (2001)'),
  ('JurTec', '+37129787822 · info@jurtec.lv · jurtec.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 9 | Lēna ielāde (3.3s); Novecojis saturs (2020)'),
  ('Latvijas Komercbanku asociācijas šķīrējtiesa', '+37167284561 · tiesa@fstiesa.lv · fstiesa.lv', 'juristi', 'todo', 'med', 'Juristi / advokāti · 35 | Nav HTTPS — nedroša; Trūkst meta apraksta (SEO)'),
  ('Ķeizarmežs', '+37167517522 · keizarmezs@keizarmezs.lv · keizarmezs.lv', 'saloni', 'todo', 'med', 'Skaistumkopšana · Ķeizarmežs | Nav HTTPS — nedroša; Trūkst meta apraksta (SEO)'),
  ('RIGANAILS', '+371 26922200 · IG @riganails', 'nagi', 'todo', 'hi', 'Nails / Brows · Centrs |  · Active IG only - no website at all.'),
  ('Nagu Meistari', 'IG @nagu_meistari', 'nagi', 'todo', 'hi', 'Nails / Lash-brow · Riga |  · 3000+ followers 24/7 booking link. No website.'),
  ('Hairport Studija', NULL, 'frizieri', 'todo', 'hi', 'Hair salon · Grizinkalns |  · Modern hair studio - Fresha-only.'),
  ('Linda Ezera PMU', 'IG @pmu_lindaezera', 'kosmetika', 'todo', 'hi', 'Permanent make-up · Riga |  · PMU lips/brows IG only.'),
  ('Santa Guru Makeup', 'IG @santaguruu', 'kosmetika', 'todo', 'hi', 'Makeup artist · Riga |  · Celebrity makeup artist IG only.'),
  ('SIBI Beauty Salon', '+371 27272510 · IG @sibi.beautysalon', 'nagi', 'todo', 'hi', 'Full beauty (hair/nails/spa) · Old Riga |  · Strong brand good reviews - only Versum booking page.'),
  ('Skaistuma Era', 'IG @skaistumaera', 'saloni', 'todo', 'hi', 'Full beauty · Jelgava |  · Largest salon in Jelgava 150+ services IG-forward (verify site).'),
  ('Amane SPA', '+371 28213790 · amanespa@gmail.com · amanespa.lv', 'spa', 'todo', 'low', 'Spa / Beauty · Old Riga | amanespa.lv · Has site - pitch redesign/upgrade only.'),
  ('Old Riga Spa', '+371 29340341 · info@oldrigaspa.lv · oldrigaspa.lv', 'spa', 'todo', 'low', 'Spa / Massage · Old Riga | oldrigaspa.lv · Has site + Versum.'),
  ('Velvet Beauty', 'velvetbeauty.lv', 'saloni', 'todo', 'low', 'Beauty studio · Centrs | velvetbeauty.lv · Has modern-ish site.'),
  ('Siluets', '+371 25150058 · siluetsriga.lv', 'saloni', 'todo', 'low', 'Full beauty · Centrs | siluetsriga.lv · Has website.'),
  ('International Manicure Studio', '+371 20004588 · info@manikirs.lv · manikirs.lv', 'nagi', 'todo', 'low', 'Nails / Training · Riga | manikirs.lv · Has site.'),
  ('MooN Beauty Studio', 'manikirs-riga.lv', 'nagi', 'todo', 'low', 'Nails · Riga | manikirs-riga.lv · Has site.'),
  ('ONE Beauty', '+371 28857000 · IG @one.beauty.nails · onebeauty.lv', 'nagi', 'todo', 'low', 'Full beauty / Nails · Plavnieki | onebeauty.lv · Has site.'),
  ('Catrin Salons', 'catrinsalons.lv', 'saloni', 'todo', 'low', 'Full beauty · Riga | catrinsalons.lv · Has site.'),
  ('NailTime', 'IG @nailtimelv · nailtime.lv', 'nagi', 'todo', 'low', 'Nails · Centrs | nailtime.lv · Has site.'),
  ('NailBee', 'nailbee.lv', 'nagi', 'todo', 'low', 'Nails · Riga | nailbee.lv · Has site.'),
  ('Divi Meistari', 'IG @divimeistari · divimeistari.lv', 'nagi', 'todo', 'low', 'Nails / Hair · Centrs | divimeistari.lv · Has site.'),
  ('Grieze', 'grieze.lv', 'saloni', 'todo', 'low', 'Full beauty · Riga | grieze.lv · Has site.'),
  ('HairRiga Olimpia', '+371 25908271 · hairriga.com', 'frizieri', 'todo', 'low', 'Hair salon · TC Olimpia | hairriga.com · Has site (chain).'),
  ('Salons Katrina', '+371 26605502 · salonskatrina@gmail.com · salonskatrina.lv', 'saloni', 'todo', 'low', 'Hair / beauty · Riga | salonskatrina.lv · Has site + email.'),
  ('BAGIRA', '+371 22831315 · bagira.lv', 'saloni', 'todo', 'low', 'Hair / beauty studio · Ziepniekkalns | bagira.lv · Has site.'),
  ('Salons MAIJA', '+371 67505193 / +371 25400103 · maija.lv', 'saloni', 'todo', 'low', 'Hair / beauty · Riga | maija.lv · Has site (multi-location).'),
  ('Silvana', '+371 29293317 · silvana.lv', 'saloni', 'todo', 'low', 'Hair extensions / beauty · Centrs | silvana.lv · Has site.'),
  ('Saules Salons', '+371 22087688 · saulessalons.lv', 'saloni', 'todo', 'low', 'Hair / beauty · Centrs | saulessalons.lv · Has site.'),
  ('Skaistuma Pietura', 'skaistumapietura.lv', 'saloni', 'todo', 'low', 'Full beauty · Ciekurkalns | skaistumapietura.lv · Has site.'),
  ('Glorija Salons', '+371 20208118 · gloria-salons.lv', 'skropstas', 'todo', 'low', 'Full beauty / Lashes · Riga | gloria-salons.lv · Has site.'),
  ('Brows by Karlina', 'bbk.lv', 'skropstas', 'todo', 'low', 'Lash / Brow · Riga | bbk.lv · Has site.'),
  ('Lash & Brow Studio Riga', 'lashandbrow.lv', 'skropstas', 'todo', 'low', 'Lash / Brow · Riga | lashandbrow.lv · Has site.'),
  ('Nautika', '+371 29429444 / +371 63422210 · nautika.lv', 'saloni', 'todo', 'low', 'Full beauty · Liepaja | nautika.lv · Has site.'),
  ('Nova Clinic', 'arstskosmetologs.lv', 'kosmetika', 'todo', 'low', 'Aesthetic medicine · Jurmala | arstskosmetologs.lv · Has site (clinic).'),
  ('ERA Esthetic', '+371 20511113 · info@eraesthetic.lv · eraesthetic.lv', 'kosmetika', 'todo', 'low', 'Cosmetology · Jurmala | eraesthetic.lv · Has site + email.'),
  ('BABOR Beauty Spa', '+371 22333131 · info@baborbeautyspa.lv · baborbeautyspa.lv', 'spa', 'todo', 'low', 'Spa / Beauty · Centrs | baborbeautyspa.lv · Has site (brand-backed).'),
  ('Taka Spa', 'takaspa.lv', 'spa', 'todo', 'low', 'Day spa · Riga | takaspa.lv · Has site.'),
  ('VSpa', '+371 26961181 · vspa.lv', 'spa', 'todo', 'low', 'Massage / Spa · Riga | vspa.lv · Has site.');
